name: Python Pyinstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pyinstaller-build:
    runs-on: [ windows-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@version-file
        with:
          python_ver: '3.6'
          pyinstaller_ver: '==5.13.2'
          spec: 'CSVMiPiaciTu.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'CSVMiPiaciTu'
          options: --onefile, --name "CSVMiPiaciTu", --windowed, --version-file "file_version_info.txt"